name: 'semantic-versioning-calculator'
description: 'Increments the semantic version string action.'
author: 'slime-hatena'
inputs:
    VERSION:
        required: true
        description: 'Specify the current semantic version. It must be followed semantic versioning rule. This value must be specified. For example: 0.2.5, 2.10.0-develop, etc.'
    INCREMENT_MAJOR:
        required: false
        description: 'Set to "true" will increment major. The default value is "false".'
        default: 'false'
    INCREMENT_MINOR:
        required: false
        description: 'Set to "true" will increment minor. If INCREMENT_MAJOR is true, it will be ignored. The default value is "false".'
        default: 'false'
    INCREMENT_PATCH:
        required: false
        description: 'Set to "true" will increment patch. If INCREMENT_MAJOR or INCREMENT_MINOR are true, it will be ignored. The default value is "false".'
        default: 'false'
    PRERELEASE:
        required: false
        description: 'Set the value as a prerelease name if specified.'
        default: ''
    META:
        required: false
        description: 'Set the value as a meta name if specified.'
        default: ''
outputs:
    version:
        description: 'Calculated semantic version string.'
runs:
    using: 'node12'
    main: 'dist/index.js'
