name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: 'increment major'
        with:
          version: '1.2.3+develop'
          increment_major: 'true'
          increment_minor: 'false'
          increment_patch: 'false'
          prerelease: ''
          meta: ''
      - uses: ./
        name: 'increment minor'
        with:
          version: '1.2.3+develop'
          increment_major: 'false'
          increment_minor: 'true'
          increment_patch: 'false'
          prerelease: ''
          meta: ''
      - uses: ./
        name: 'increment patch'
        with:
          version: '1.2.3+develop'
          increment_major: 'false'
          increment_minor: 'false'
          increment_patch: 'true'
          prerelease: ''
          meta: ''
      - uses: ./
        name: 'add prerelease'
        with:
          version: '1.2.3+develop'
          increment_major: 'false'
          increment_minor: 'false'
          increment_patch: 'false'
          prerelease: 'main'
          meta: ''
      - uses: ./
        name: 'add meta'
        with:
          version: '1.2.3+develop'
          increment_major: 'false'
          increment_minor: 'false'
          increment_patch: 'false'
          prerelease: ''
          meta: 'release'
      - uses: ./
        name: 'add both'
        with:
          version: '1.2.3+develop'
          increment_major: 'false'
          increment_minor: 'false'
          increment_patch: 'false'
          prerelease: 'main'
          meta: 'release'
